General:
    comment:
    seed: 2021
    fp16: False
    disable_loggers: True
    amp_level: O2
    precision: 32
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 200
    grad_acc: 2
    frozen_bn: False
    patience: 10
    server: train
    log_path: logs/

Data:
    dataset_name: camel_data
    data_shuffle: False
    data_dir: IbotViTBaseCOADCamelyon16/pt_files/
    label_dir: dataset_csv/ibotvitbasecoadcamelyon16/
    fold: 0
    nfold: 1

    train_dataloader:
        batch_size: 1
        num_workers: 0

    test_dataloader:
        batch_size: 1
        num_workers: 0

Model:
    name: TransMIL
    n_classes: 2
    input_dim: 387

Optimizer:
    opt: lookahead_radam
    lr: 0.0002
    opt_eps: null
    opt_betas: null
    momentum: null
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss
